apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
data:
  APP_PORT: "3000"
  APP_ENV: "production"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "MyStrongPass123"

